--- !ditz.rubyforge.org,2008-03-06/project 
name: gtkmateview
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: gtkmateview
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-10-14 20:42:27.460493 Z
    - Daniel Lucraft <dan@fluentradical.com>
    - created
    - Synched with Redcar 0.1 release.
